openapi: 3.0.3
info:
  title: Ragnance API
  version: "1.0.0"
  description: |
    API pour la gestion budgétaire Ragnance.
servers:
  - url: /api/v1

paths: {}

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
